### ISSUE TITLE
I don't agree with the use of Flesch-Kincaid

### ISSUE THREAD

**Issue by ghost** [words/flesch-kincaid#13]
I don't like or agree with the use of this readability test. It consistently scores my writing "Difficult to read," "Very difficult to read" or occasionally "Fairly difficult to read" or "Plain English." I know my writing isn't difficult to read. I've been writing most of my life. I have a BA in history that required me to write a 100-page senior thesis. I've published original content on a news website for nearly five years. I haven't received one complaint about the readability of my writing in that period of time. I would suggest that the standards used by Flesch-Kincaid are antiquated, since they do not account for modern writing styles synonymous with web-based applications, nor do they take into account the fact that people today have a dictionary at their fingertips. It's called a smartphone. So the "need" to dumb down writing to a 7th grade level--or whatever it is--is not the same as it once was. What really galls me is that Yoast employs this tool to grade people who use its plugin when the plugin itself contains sub-standard English, e.g. "Keywords have been previously used before." Keywords have been PREVIOUSLY used BEFORE. What is wrong with that sentence? A: It is redundant to use "previously" and "before" in the context of the above statement because they mean the same thing. That is an example of "Difficult to read" writing, and I have to stare that in the face at the same time I'm being told my writing is weak. I have no problem with the use of a readability measurement tool being part of the plugin, but make it a good one, give us a choice or allow us to turn it off if we don't want (or need) the help.

**Comment by wooorm** [comment]
Hey @JoshPopichak, I see you just created GitHub so I’ll respond relatively nicely, but you have no clue what you’re doing and come across as uninformed and rude.

- You are wrong about readability not being important. Go learn something from Hemingway
- Open Source means that people can read code. [Here’s a NYTimes article](https://www.nytimes.com/2019/06/11/magazine/letter-of-recommendation-bug-fixes-git.html) for you that was posted today with some more info. More info can also be found in [Open Source Guides](https://opensource.guide)
- What you’re doing by yelling here is essentially posting on Wikipedia’s page about [Flesch–Kincaid](https://en.wikipedia.org/wiki/Flesch–Kincaid_readability_tests) that something sucks. It’s a description of something! (And this is code about that thing). Wikipedia (or here) is not the place to say something sucks.
- Yoast does not use this project (words/flesch-kincaid). If you have a problem with yoast go yell at yoast (but don’t because your wrong)

**Comment by ghost** [comment]
I was instructed by YOAST to submit this here. All I did was follow their link. <img width="580" alt="Yoast" src="https://user-images.githubusercontent.com/51709008/59284716-bc7fe180-8c3a-11e9-827b-989344765c99.png">

**Comment by wooorm** [comment]
The link text references a different project
